### PR TITLE
add MinUpgradableVersion

### LINKED ISSUE #30: Add `MinUpgradableVersion` in `Version` field
It's good to add `MinUpgradableVersion` to restrict users to upgrade the system from a very old version. Sometimes, we may have some transformation in a specific version, so we may need users to upgrade to that version before upgrading to the latest version.

https://github.com/harvester/upgrade-responder/blob/032365e51c204dfc4aa8793410f5e6a0114c276e/upgraderesponder/service.go#L63

https://github.com/harvester/harvester/issues/1849

### PR DESCRIPTION
**Pull request by FrankYang0529**
close #30 
related https://github.com/harvester/harvester/issues/1849

### CODE REVIEW

**Comment by PhanLe1010** [comment]
I am thinking if we should organize the Version struct to have:
* Default fields: Name, ReleaseDate, Tags
* Everything else (e.g., MinUpgradableVersion) can be put input a new field, ExtraInfo.

By doing this, we can support dynamically new fields without having to modify the source code. For example, other projects might want to put something new into the Version struct. 

How do you think @FrankYang0529

**Comment by FrankYang0529** [comment]
Sounds good to me, but we may need some update in Harvester. @bk201 WDYT? Thank you.

**Comment by bk201** [comment]
It's a good idea but user's clusters already rely on that field.
If we move it, users will see all versions https://github.com/harvester/harvester/blob/dd3c5f4b59ddd0cebcb8b5d71f716067b842c06c/pkg/controller/master/upgrade/version_syncer.go#L193
Need to figure out how to handle existing clusters.

**Comment by FrankYang0529** [comment]
How about we still add `MinUpgradableVersion` as a default field, but also add `ExtraInfo` field for future change?

**Comment by PhanLe1010** [comment]
>  How about we still add MinUpgradableVersion as a default field, but also add ExtraInfo field for future change?

Sounds good to me

**Comment by FrankYang0529** [comment]
> > How about we still add MinUpgradableVersion as a default field, but also add ExtraInfo field for future change?
> 
> Sounds good to me

Thanks, I add the `ExtraInfo` field to `Version`. Please help me review it again.

**Review by PhanLe1010 — APPROVED** [review]
LGTM

**Pull request merged**
